language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip

sudo: false

before_install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - go run pinyin/main.go abc
  - $HOME/gopath/bin/goveralls -repotoken WAzmh3gmiQEUYEHM2wkwSH4oTrshvMmll
